// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSzv9s5Mf9_LGwSbWrmwkXtZuE-xJ9rWQ',
    appId: '1:619702604255:web:809d3959513b98a955746a',
    messagingSenderId: '619702604255',
    projectId: 'homesahulat-19b31',
    authDomain: 'homesahulat-19b31.firebaseapp.com',
    storageBucket: 'homesahulat-19b31.appspot.com',
    measurementId: 'G-JRFK1LYWB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWejiMOhHdNAV9cuzh9MICSYdY1MMRd4',
    appId: '1:619702604255:android:41c4140a97a7868b55746a',
    messagingSenderId: '619702604255',
    projectId: 'homesahulat-19b31',
    storageBucket: 'homesahulat-19b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMVhwVhLY4q9iyL75Ugo3lBjR4VNOgHFg',
    appId: '1:619702604255:ios:9b4097fa5ed7e54055746a',
    messagingSenderId: '619702604255',
    projectId: 'homesahulat-19b31',
    storageBucket: 'homesahulat-19b31.appspot.com',
    iosBundleId: 'com.example.homesahulatFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMVhwVhLY4q9iyL75Ugo3lBjR4VNOgHFg',
    appId: '1:619702604255:ios:adb28b87278ed52155746a',
    messagingSenderId: '619702604255',
    projectId: 'homesahulat-19b31',
    storageBucket: 'homesahulat-19b31.appspot.com',
    iosBundleId: 'com.example.homesahulatFyp.RunnerTests',
  );
}
